"use client";

import { useState } from "react";
import { Download, RefreshCw, CheckCircle, XCircle, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProcessingResult } from "@/types";

interface ResultViewProps {
  result: ProcessingResult;
  onIterationRequest: (newPrompt: string) => void;
  onReset: () => void;
  maxIterations: number;
}

export function ResultView({
  result,
  onIterationRequest,
  onReset,
  maxIterations,
}: ResultViewProps) {
  const [newPrompt, setNewPrompt] = useState("");
  const [showIterationInput, setShowIterationInput] = useState(false);

  const handleDownload = () => {
    const link = document.createElement("a");
    link.href = result.imageUrl;
    link.download = `revised-logo-iteration-${result.iteration}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleIterate = () => {
    if (!newPrompt.trim()) {
      alert("Please enter a revision prompt");
      return;
    }
    onIterationRequest(newPrompt);
    setNewPrompt("");
    setShowIterationInput(false);
  };

  const canIterate = result.iteration < maxIterations;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg p-8">
        {/* Header */}
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4">
            <CheckCircle className="w-8 h-8 text-green-600" />
          </div>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Revision Complete!
          </h2>
          <p className="text-gray-600">
            Iteration {result.iteration} of {maxIterations}
          </p>
        </div>

        {/* Result Image */}
        <div className="mb-6">
          <div className="bg-gray-50 rounded-lg p-8 flex items-center justify-center">
            <img
              src={result.imageUrl}
              alt="Revised Logo"
              className="max-w-full h-auto border-2 border-gray-200 rounded-lg shadow-md"
              style={{ maxHeight: "400px" }}
            />
          </div>
        </div>

        {/* Enhanced Prompt */}
        <div className="mb-6 bg-blue-50 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-gray-700 mb-2">
            Enhanced Prompt (Generated by AI):
          </h3>
          <p className="text-sm text-gray-600 italic">
            "{result.enhancedPrompt}"
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-3 mb-6">
          <Button
            onClick={handleDownload}
            variant="default"
            className="flex-1"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Result
          </Button>
          <Button
            onClick={onReset}
            variant="outline"
            className="flex-1"
          >
            <RotateCcw className="w-4 h-4 mr-2" />
            Start Over
          </Button>
        </div>

        {/* Iteration Section */}
        <div className="border-t pt-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-3">
            Not satisfied with the result?
          </h3>

          {canIterate ? (
            <>
              {!showIterationInput ? (
                <Button
                  onClick={() => setShowIterationInput(true)}
                  variant="outline"
                  className="w-full"
                >
                  <RefreshCw className="w-4 h-4 mr-2" />
                  Request Another Iteration
                </Button>
              ) : (
                <div className="space-y-3">
                  <textarea
                    value={newPrompt}
                    onChange={(e) => setNewPrompt(e.target.value)}
                    placeholder="Describe what you'd like to change... (e.g., 'Make it simpler' or 'Add more contrast')"
                    className="w-full min-h-[100px] px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                  />
                  <div className="flex gap-2">
                    <Button
                      onClick={handleIterate}
                      className="flex-1"
                    >
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Generate Iteration {result.iteration + 1}
                    </Button>
                    <Button
                      onClick={() => {
                        setShowIterationInput(false);
                        setNewPrompt("");
                      }}
                      variant="outline"
                    >
                      Cancel
                    </Button>
                  </div>
                  <p className="text-xs text-gray-500">
                    Note: Iterations use only Pix2Pix for refinement (CycleGAN is skipped)
                  </p>
                </div>
              )}
            </>
          ) : (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <XCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-red-900 mb-1">
                    Maximum Iterations Reached
                  </p>
                  <p className="text-sm text-red-700">
                    Our trained model is not yet sufficient to generate your desired
                    output. You may start over with a different image or prompt.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
